<a href="https://colab.research.google.com/github/Innovatewithapple/Classification/blob/main/adultincomeClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#model + preprocessing
from sklearn.model_selection import train_test_split,GridSearchCV,cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

#model
from sklearn.linear_model import LogisticRegression

#Evaluation
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [6]:
df = pd.read_csv('/content/adult.csv',skiprows=1)
df.head(5)

   age  workclass  fnlwgt  ...  hours-per-week  native-country  incomes
0   39          8   77516  ...              40              40        1
1   50          7   83311  ...              13              40        1
2   38          5  215646  ...              40              40        1
3   53          5  234721  ...              40              40        1
4   28          5  338409  ...              40               6        1

[5 rows x 15 columns]

In [7]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
incomes           0
dtype: int64

In [8]:
df.describe()

                age     workclass  ...  native-country       incomes
count  48842.000000  48842.000000  ...    48842.000000  48842.000000
mean      38.643585      4.870439  ...       37.749355      1.239282
std       13.710510      1.464234  ...        7.775343      0.426649
min       17.000000      1.000000  ...        1.000000      1.000000
25%       28.000000      5.000000  ...       40.000000      1.000000
50%       37.000000      5.000000  ...       40.000000      1.000000
75%       48.000000      5.000000  ...       40.000000      1.000000
max       90.000000      9.000000  ...       42.000000      2.000000

[8 rows x 15 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       48842 non-null  int64
 2   fnlwgt          48842 non-null  int64
 3   education       48842 non-null  int64
 4   education-num   48842 non-null  int64
 5   marital-status  48842 non-null  int64
 6   occupation      48842 non-null  int64
 7   relationship    48842 non-null  int64
 8   race            48842 non-null  int64
 9   sex             48842 non-null  int64
 10  capital-gain    48842 non-null  int64
 11  capital-loss    48842 non-null  int64
 12  hours-per-week  48842 non-null  int64
 13  native-country  48842 non-null  int64
 14  incomes         48842 non-null  int64
dtypes: int64(15)
memory usage: 5.6 MB

In [10]:
x = df.drop(columns='incomes')
y = df['incomes']

In [17]:
y

0        1
1        1
2        1
3        1
4        1
        ..
48837    1
48838    1
48839    1
48840    1
48841    2
Name: incomes, Length: 48842, dtype: int64

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [19]:
scalingColumns = x.columns
preprocessor = ColumnTransformer([
    ('nums',StandardScaler(),scalingColumns)
])

In [20]:
#Logistic
logisticPipeline = Pipeline([
    ('preprocessor',preprocessor),
    ('model',LogisticRegression())
])

In [21]:
logisticPipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('nums', StandardScaler(),
                                                  Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country'],
      dtype='object'))])),
                ('model', LogisticRegression())])

In [24]:
cross_score = cross_validate(logisticPipeline,x_train,y_train,cv=5,scoring=["accuracy", "precision", "recall", "f1"])
cross_score

{'fit_time': array([0.05704355, 0.05195451, 0.05514336, 0.05436158, 0.05306339]),
 'score_time': array([0.02421927, 0.01930118, 0.01917291, 0.01956367, 0.01931596]),
 'test_accuracy': array([0.82728868, 0.82509506, 0.82787365, 0.82114653, 0.82828726]),
 'test_precision': array([0.84571821, 0.84708528, 0.84722701, 0.8419698 , 0.84742552]),
 'test_recall': array([0.94587332, 0.94010367, 0.94432713, 0.94202342, 0.94471108]),
 'test_f1': array([0.89299629, 0.89117379, 0.89314571, 0.8891909 , 0.89342774])}